#ifndef DEVICE_CAMERA_EVENT_STATE_TYPE_H_
#define DEVICE_CAMERA_EVENT_STATE_TYPE_H_


typedef enum
{
    DEVICE_EVENT_NONE,
    DEVICE_EVENT_STATE_PLUGGED = 1,
    DEVICE_EVENT_STATE_UNPLUGGED,
    DEVICE_EVENT_STATE_UNSUPPORTED_PLUGGED,
    DEVICE_EVENT_STATE_UNSUPPORTED_UNPLUGGED,
    DEVICE_EVENT_STATE_DUPLICATED_PLUGGED,
    DEVICE_EVENT_STATE_DUPLICATED_UNPLUGGED,
    DEVICE_EVENT_STATE_BUILT_IN_UP,
    DEVICE_EVENT_STATE_BUILT_IN_DOWN,
    DEVICE_EVENT_STATE_UPDATING,
    DEVICE_EVENT_STATE_UPDATE_FINISHED,
    DEVICE_EVENT_STATE_UPDATE_FAIL
} DEVICE_EVENT_STATE_T;

#endif /* DEVICE_CAMERA_EVENT_STATE_TYPE_H_ */
